# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tbuchy/surf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tbuchy/surf

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tbuchy/surf/CMakeFiles /home/tbuchy/surf/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tbuchy/surf/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eval

# Build rule for target.
eval: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eval
.PHONY : eval

# fast build rule for target.
eval/fast:
	$(MAKE) -f CMakeFiles/eval.dir/build.make CMakeFiles/eval.dir/build
.PHONY : eval/fast

#=============================================================================
# Target rules for targets named train

# Build rule for target.
train: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 train
.PHONY : train

# fast build rule for target.
train/fast:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/build
.PHONY : train/fast

# target to build an object file
eval.o:
	$(MAKE) -f CMakeFiles/eval.dir/build.make CMakeFiles/eval.dir/eval.o
.PHONY : eval.o

# target to preprocess a source file
eval.i:
	$(MAKE) -f CMakeFiles/eval.dir/build.make CMakeFiles/eval.dir/eval.i
.PHONY : eval.i

# target to generate assembly for a file
eval.s:
	$(MAKE) -f CMakeFiles/eval.dir/build.make CMakeFiles/eval.dir/eval.s
.PHONY : eval.s

# target to build an object file
extractor.o:
	$(MAKE) -f CMakeFiles/eval.dir/build.make CMakeFiles/eval.dir/extractor.o
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/extractor.o
.PHONY : extractor.o

# target to preprocess a source file
extractor.i:
	$(MAKE) -f CMakeFiles/eval.dir/build.make CMakeFiles/eval.dir/extractor.i
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/extractor.i
.PHONY : extractor.i

# target to generate assembly for a file
extractor.s:
	$(MAKE) -f CMakeFiles/eval.dir/build.make CMakeFiles/eval.dir/extractor.s
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/extractor.s
.PHONY : extractor.s

# target to build an object file
train.o:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/train.o
.PHONY : train.o

# target to preprocess a source file
train.i:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/train.i
.PHONY : train.i

# target to generate assembly for a file
train.s:
	$(MAKE) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/train.s
.PHONY : train.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... eval"
	@echo "... rebuild_cache"
	@echo "... train"
	@echo "... eval.o"
	@echo "... eval.i"
	@echo "... eval.s"
	@echo "... extractor.o"
	@echo "... extractor.i"
	@echo "... extractor.s"
	@echo "... train.o"
	@echo "... train.i"
	@echo "... train.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

